import { db } from "@workspace/db";
import { versesTable, booksTable, devotionalsTable, dailyVersesTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Seeding database...");

  await db.delete(dailyVersesTable);
  await db.delete(devotionalsTable);
  await db.delete(versesTable);
  await db.delete(booksTable);

  const books = [
    { name: "Genesis", testament: "Old Testament", chapters: 50, ordering: 1 },
    { name: "Exodus", testament: "Old Testament", chapters: 40, ordering: 2 },
    { name: "Leviticus", testament: "Old Testament", chapters: 27, ordering: 3 },
    { name: "Numbers", testament: "Old Testament", chapters: 36, ordering: 4 },
    { name: "Deuteronomy", testament: "Old Testament", chapters: 34, ordering: 5 },
    { name: "Joshua", testament: "Old Testament", chapters: 24, ordering: 6 },
    { name: "Judges", testament: "Old Testament", chapters: 21, ordering: 7 },
    { name: "Ruth", testament: "Old Testament", chapters: 4, ordering: 8 },
    { name: "1 Samuel", testament: "Old Testament", chapters: 31, ordering: 9 },
    { name: "2 Samuel", testament: "Old Testament", chapters: 24, ordering: 10 },
    { name: "1 Kings", testament: "Old Testament", chapters: 22, ordering: 11 },
    { name: "2 Kings", testament: "Old Testament", chapters: 25, ordering: 12 },
    { name: "1 Chronicles", testament: "Old Testament", chapters: 29, ordering: 13 },
    { name: "2 Chronicles", testament: "Old Testament", chapters: 36, ordering: 14 },
    { name: "Ezra", testament: "Old Testament", chapters: 10, ordering: 15 },
    { name: "Nehemiah", testament: "Old Testament", chapters: 13, ordering: 16 },
    { name: "Esther", testament: "Old Testament", chapters: 10, ordering: 17 },
    { name: "Job", testament: "Old Testament", chapters: 42, ordering: 18 },
    { name: "Psalms", testament: "Old Testament", chapters: 150, ordering: 19 },
    { name: "Proverbs", testament: "Old Testament", chapters: 31, ordering: 20 },
    { name: "Ecclesiastes", testament: "Old Testament", chapters: 12, ordering: 21 },
    { name: "Song of Solomon", testament: "Old Testament", chapters: 8, ordering: 22 },
    { name: "Isaiah", testament: "Old Testament", chapters: 66, ordering: 23 },
    { name: "Jeremiah", testament: "Old Testament", chapters: 52, ordering: 24 },
    { name: "Lamentations", testament: "Old Testament", chapters: 5, ordering: 25 },
    { name: "Ezekiel", testament: "Old Testament", chapters: 48, ordering: 26 },
    { name: "Daniel", testament: "Old Testament", chapters: 12, ordering: 27 },
    { name: "Hosea", testament: "Old Testament", chapters: 14, ordering: 28 },
    { name: "Joel", testament: "Old Testament", chapters: 3, ordering: 29 },
    { name: "Amos", testament: "Old Testament", chapters: 9, ordering: 30 },
    { name: "Obadiah", testament: "Old Testament", chapters: 1, ordering: 31 },
    { name: "Jonah", testament: "Old Testament", chapters: 4, ordering: 32 },
    { name: "Micah", testament: "Old Testament", chapters: 7, ordering: 33 },
    { name: "Nahum", testament: "Old Testament", chapters: 3, ordering: 34 },
    { name: "Habakkuk", testament: "Old Testament", chapters: 3, ordering: 35 },
    { name: "Zephaniah", testament: "Old Testament", chapters: 3, ordering: 36 },
    { name: "Haggai", testament: "Old Testament", chapters: 2, ordering: 37 },
    { name: "Zechariah", testament: "Old Testament", chapters: 14, ordering: 38 },
    { name: "Malachi", testament: "Old Testament", chapters: 4, ordering: 39 },
    { name: "Matthew", testament: "New Testament", chapters: 28, ordering: 40 },
    { name: "Mark", testament: "New Testament", chapters: 16, ordering: 41 },
    { name: "Luke", testament: "New Testament", chapters: 24, ordering: 42 },
    { name: "John", testament: "New Testament", chapters: 21, ordering: 43 },
    { name: "Acts", testament: "New Testament", chapters: 28, ordering: 44 },
    { name: "Romans", testament: "New Testament", chapters: 16, ordering: 45 },
    { name: "1 Corinthians", testament: "New Testament", chapters: 16, ordering: 46 },
    { name: "2 Corinthians", testament: "New Testament", chapters: 13, ordering: 47 },
    { name: "Galatians", testament: "New Testament", chapters: 6, ordering: 48 },
    { name: "Ephesians", testament: "New Testament", chapters: 6, ordering: 49 },
    { name: "Philippians", testament: "New Testament", chapters: 4, ordering: 50 },
    { name: "Colossians", testament: "New Testament", chapters: 4, ordering: 51 },
    { name: "1 Thessalonians", testament: "New Testament", chapters: 5, ordering: 52 },
    { name: "2 Thessalonians", testament: "New Testament", chapters: 3, ordering: 53 },
    { name: "1 Timothy", testament: "New Testament", chapters: 6, ordering: 54 },
    { name: "2 Timothy", testament: "New Testament", chapters: 4, ordering: 55 },
    { name: "Titus", testament: "New Testament", chapters: 3, ordering: 56 },
    { name: "Philemon", testament: "New Testament", chapters: 1, ordering: 57 },
    { name: "Hebrews", testament: "New Testament", chapters: 13, ordering: 58 },
    { name: "James", testament: "New Testament", chapters: 5, ordering: 59 },
    { name: "1 Peter", testament: "New Testament", chapters: 5, ordering: 60 },
    { name: "2 Peter", testament: "New Testament", chapters: 3, ordering: 61 },
    { name: "1 John", testament: "New Testament", chapters: 5, ordering: 62 },
    { name: "2 John", testament: "New Testament", chapters: 1, ordering: 63 },
    { name: "3 John", testament: "New Testament", chapters: 1, ordering: 64 },
    { name: "Jude", testament: "New Testament", chapters: 1, ordering: 65 },
    { name: "Revelation", testament: "New Testament", chapters: 22, ordering: 66 },
  ];

  await db.insert(booksTable).values(books);
  console.log(`Inserted ${books.length} books`);

  const verses = [
    { book: "Genesis", chapter: 1, verseNumber: 1, text: "In the beginning God created the heaven and the earth.", version: "KJV" },
    { book: "Genesis", chapter: 1, verseNumber: 2, text: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.", version: "KJV" },
    { book: "Genesis", chapter: 1, verseNumber: 3, text: "And God said, Let there be light: and there was light.", version: "KJV" },
    { book: "Genesis", chapter: 1, verseNumber: 4, text: "And God saw the light, that it was good: and God divided the light from the darkness.", version: "KJV" },
    { book: "Genesis", chapter: 1, verseNumber: 5, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 1, text: "The Lord is my shepherd; I shall not want.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 2, text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 3, text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 4, text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 5, text: "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.", version: "KJV" },
    { book: "Psalms", chapter: 23, verseNumber: 6, text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever.", version: "KJV" },
    { book: "Psalms", chapter: 46, verseNumber: 10, text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", version: "KJV" },
    { book: "Psalms", chapter: 119, verseNumber: 105, text: "Thy word is a lamp unto my feet, and a light unto my path.", version: "KJV" },
    { book: "Psalms", chapter: 27, verseNumber: 1, text: "The Lord is my light and my salvation; whom shall I fear? the Lord is the strength of my life; of whom shall I be afraid?", version: "KJV" },
    { book: "Psalms", chapter: 34, verseNumber: 8, text: "O taste and see that the Lord is good: blessed is the man that trusteth in him.", version: "KJV" },
    { book: "Psalms", chapter: 37, verseNumber: 4, text: "Delight thyself also in the Lord: and he shall give thee the desires of thine heart.", version: "KJV" },
    { book: "Psalms", chapter: 91, verseNumber: 1, text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", version: "KJV" },
    { book: "Psalms", chapter: 91, verseNumber: 2, text: "I will say of the Lord, He is my refuge and my fortress: my God; in him will I trust.", version: "KJV" },
    { book: "Proverbs", chapter: 3, verseNumber: 5, text: "Trust in the Lord with all thine heart; and lean not unto thine own understanding.", version: "KJV" },
    { book: "Proverbs", chapter: 3, verseNumber: 6, text: "In all thy ways acknowledge him, and he shall direct thy paths.", version: "KJV" },
    { book: "Proverbs", chapter: 4, verseNumber: 23, text: "Keep thy heart with all diligence; for out of it are the issues of life.", version: "KJV" },
    { book: "Proverbs", chapter: 16, verseNumber: 3, text: "Commit thy works unto the Lord, and thy thoughts shall be established.", version: "KJV" },
    { book: "Isaiah", chapter: 40, verseNumber: 31, text: "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", version: "KJV" },
    { book: "Isaiah", chapter: 41, verseNumber: 10, text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", version: "KJV" },
    { book: "Isaiah", chapter: 43, verseNumber: 2, text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee.", version: "KJV" },
    { book: "Jeremiah", chapter: 29, verseNumber: 11, text: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.", version: "KJV" },
    { book: "Jeremiah", chapter: 33, verseNumber: 3, text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.", version: "KJV" },
    { book: "Lamentations", chapter: 3, verseNumber: 22, text: "It is of the Lord's mercies that we are not consumed, because his compassions fail not.", version: "KJV" },
    { book: "Lamentations", chapter: 3, verseNumber: 23, text: "They are new every morning: great is thy faithfulness.", version: "KJV" },
    { book: "Matthew", chapter: 5, verseNumber: 4, text: "Blessed are they that mourn: for they shall be comforted.", version: "KJV" },
    { book: "Matthew", chapter: 6, verseNumber: 33, text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", version: "KJV" },
    { book: "Matthew", chapter: 11, verseNumber: 28, text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", version: "KJV" },
    { book: "Matthew", chapter: 11, verseNumber: 29, text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.", version: "KJV" },
    { book: "Matthew", chapter: 28, verseNumber: 20, text: "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you always, even unto the end of the world. Amen.", version: "KJV" },
    { book: "John", chapter: 3, verseNumber: 16, text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", version: "KJV" },
    { book: "John", chapter: 8, verseNumber: 32, text: "And ye shall know the truth, and the truth shall make you free.", version: "KJV" },
    { book: "John", chapter: 14, verseNumber: 6, text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.", version: "KJV" },
    { book: "John", chapter: 14, verseNumber: 27, text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", version: "KJV" },
    { book: "John", chapter: 16, verseNumber: 33, text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.", version: "KJV" },
    { book: "Romans", chapter: 8, verseNumber: 28, text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", version: "KJV" },
    { book: "Romans", chapter: 8, verseNumber: 31, text: "What shall we then say to these things? If God be for us, who can be against us?", version: "KJV" },
    { book: "Romans", chapter: 8, verseNumber: 38, text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come.", version: "KJV" },
    { book: "Romans", chapter: 8, verseNumber: 39, text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.", version: "KJV" },
    { book: "Romans", chapter: 12, verseNumber: 2, text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.", version: "KJV" },
    { book: "1 Corinthians", chapter: 13, verseNumber: 4, text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.", version: "KJV" },
    { book: "1 Corinthians", chapter: 13, verseNumber: 13, text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.", version: "KJV" },
    { book: "2 Corinthians", chapter: 5, verseNumber: 7, text: "For we walk by faith, not by sight.", version: "KJV" },
    { book: "2 Corinthians", chapter: 12, verseNumber: 9, text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.", version: "KJV" },
    { book: "Galatians", chapter: 5, verseNumber: 22, text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.", version: "KJV" },
    { book: "Ephesians", chapter: 2, verseNumber: 8, text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", version: "KJV" },
    { book: "Ephesians", chapter: 3, verseNumber: 20, text: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us.", version: "KJV" },
    { book: "Ephesians", chapter: 6, verseNumber: 10, text: "Finally, my brethren, be strong in the Lord, and in the power of his might.", version: "KJV" },
    { book: "Philippians", chapter: 4, verseNumber: 6, text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", version: "KJV" },
    { book: "Philippians", chapter: 4, verseNumber: 7, text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", version: "KJV" },
    { book: "Philippians", chapter: 4, verseNumber: 13, text: "I can do all things through Christ which strengtheneth me.", version: "KJV" },
    { book: "Colossians", chapter: 3, verseNumber: 23, text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", version: "KJV" },
    { book: "2 Timothy", chapter: 1, verseNumber: 7, text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", version: "KJV" },
    { book: "Hebrews", chapter: 11, verseNumber: 1, text: "Now faith is the substance of things hoped for, the evidence of things not seen.", version: "KJV" },
    { book: "Hebrews", chapter: 12, verseNumber: 2, text: "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.", version: "KJV" },
    { book: "Hebrews", chapter: 13, verseNumber: 5, text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.", version: "KJV" },
    { book: "James", chapter: 1, verseNumber: 5, text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.", version: "KJV" },
    { book: "1 Peter", chapter: 5, verseNumber: 7, text: "Casting all your care upon him; for he careth for you.", version: "KJV" },
    { book: "1 John", chapter: 4, verseNumber: 19, text: "We love him, because he first loved us.", version: "KJV" },
    { book: "Revelation", chapter: 21, verseNumber: 4, text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.", version: "KJV" },
    { book: "Deuteronomy", chapter: 31, verseNumber: 6, text: "Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", version: "KJV" },
    { book: "Joshua", chapter: 1, verseNumber: 9, text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.", version: "KJV" },
    { book: "Psalms", chapter: 46, verseNumber: 1, text: "God is our refuge and strength, a very present help in trouble.", version: "KJV" },
    { book: "Psalms", chapter: 55, verseNumber: 22, text: "Cast thy burden upon the Lord, and he shall sustain thee: he shall never suffer the righteous to be moved.", version: "KJV" },
    { book: "Psalms", chapter: 62, verseNumber: 1, text: "Truly my soul waiteth upon God: from him cometh my salvation.", version: "KJV" },
    { book: "Psalms", chapter: 100, verseNumber: 4, text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.", version: "KJV" },
    { book: "Psalms", chapter: 103, verseNumber: 1, text: "Bless the Lord, O my soul: and all that is within me, bless his holy name.", version: "KJV" },
    { book: "Psalms", chapter: 118, verseNumber: 24, text: "This is the day which the Lord hath made; we will rejoice and be glad in it.", version: "KJV" },
    { book: "Psalms", chapter: 121, verseNumber: 1, text: "I will lift up mine eyes unto the hills, from whence cometh my help.", version: "KJV" },
    { book: "Psalms", chapter: 121, verseNumber: 2, text: "My help cometh from the Lord, which made heaven and earth.", version: "KJV" },
    { book: "Psalms", chapter: 139, verseNumber: 14, text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", version: "KJV" },
    { book: "Psalms", chapter: 143, verseNumber: 8, text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.", version: "KJV" },
    { book: "Proverbs", chapter: 18, verseNumber: 10, text: "The name of the Lord is a strong tower: the righteous runneth into it, and is safe.", version: "KJV" },
    { book: "Isaiah", chapter: 26, verseNumber: 3, text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", version: "KJV" },
    { book: "Isaiah", chapter: 40, verseNumber: 29, text: "He giveth power to the faint; and to them that have no might he increaseth strength.", version: "KJV" },
    { book: "Nahum", chapter: 1, verseNumber: 7, text: "The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", version: "KJV" },
    { book: "Zephaniah", chapter: 3, verseNumber: 17, text: "The Lord thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.", version: "KJV" },
    { book: "Matthew", chapter: 7, verseNumber: 7, text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", version: "KJV" },
    { book: "Mark", chapter: 11, verseNumber: 24, text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.", version: "KJV" },
    { book: "Luke", chapter: 1, verseNumber: 37, text: "For with God nothing shall be impossible.", version: "KJV" },
    { book: "John", chapter: 10, verseNumber: 10, text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.", version: "KJV" },
    { book: "John", chapter: 15, verseNumber: 5, text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.", version: "KJV" },
    { book: "Romans", chapter: 5, verseNumber: 8, text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.", version: "KJV" },
    { book: "Romans", chapter: 15, verseNumber: 13, text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", version: "KJV" },
    { book: "Galatians", chapter: 2, verseNumber: 20, text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.", version: "KJV" },
    { book: "Philippians", chapter: 1, verseNumber: 6, text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.", version: "KJV" },
    { book: "1 Thessalonians", chapter: 5, verseNumber: 16, text: "Rejoice evermore.", version: "KJV" },
    { book: "1 Thessalonians", chapter: 5, verseNumber: 17, text: "Pray without ceasing.", version: "KJV" },
    { book: "1 Thessalonians", chapter: 5, verseNumber: 18, text: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you.", version: "KJV" },
    { book: "James", chapter: 4, verseNumber: 8, text: "Draw nigh to God, and he will draw nigh to you.", version: "KJV" },
    { book: "1 John", chapter: 1, verseNumber: 9, text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.", version: "KJV" },
    { book: "Revelation", chapter: 3, verseNumber: 20, text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me.", version: "KJV" },
  ];

  await db.insert(versesTable).values(verses);
  console.log(`Inserted ${verses.length} verses`);

  const devotionals = [
    {
      title: "Finding Peace in the Storm",
      content: "Life often brings unexpected storms — moments of uncertainty, fear, and doubt. Yet in the midst of these storms, God offers us His perfect peace. This peace doesn't come from the absence of trouble, but from the presence of God in our lives.\n\nWhen Jesus calmed the storm on the Sea of Galilee, He didn't remove His disciples from the storm first. He was right there with them, speaking peace into their chaos. In the same way, God is with you today, whatever storm you may be facing.\n\nTake a moment to breathe deeply and remember: the One who created the winds and the waves is the same One who holds you in His hands. He has not forgotten you. He is not surprised by your circumstances. And He is working all things together for your good.\n\nPrayer: Lord, I bring my storms to You today. Help me to trust in Your sovereignty and find peace in Your presence. Calm my anxious heart and remind me that You are in control. Amen.",
      verseReference: "John 14:27",
      verseText: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
      category: "Peace",
      readTime: 4,
      date: "2026-03-15",
    },
    {
      title: "Strength in Weakness",
      content: "There's a beautiful paradox in the Christian life: when we are weak, we are strong. The world tells us to be self-sufficient, to pull ourselves up by our bootstraps. But God's economy works differently.\n\nPaul discovered this truth through his own suffering. Three times he pleaded with the Lord to remove his thorn in the flesh. God's answer wasn't removal — it was revelation. \"My grace is sufficient for you, for my strength is made perfect in weakness.\"\n\nWhen we acknowledge our weakness, we create space for God's strength to flow through us. It's not about pretending to have it all together. It's about honestly admitting our need and watching God show up in powerful ways.\n\nToday, instead of hiding your struggles, bring them to God. Let His grace meet you exactly where you are.\n\nPrayer: Father, I confess my weakness before You. Thank You that Your grace is enough. Fill me with Your strength today. Let my life be a testimony of Your power at work in human frailty. Amen.",
      verseReference: "2 Corinthians 12:9",
      verseText: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.",
      category: "Strength",
      readTime: 5,
      date: "2026-03-14",
    },
    {
      title: "Walking by Faith",
      content: "Faith is not the absence of doubt — it's choosing to trust God despite our doubts. Abraham didn't have a GPS showing him exactly where God was leading. He simply obeyed and took the next step.\n\nWalking by faith means making decisions based on God's promises rather than our circumstances. It means looking beyond what our eyes can see to what our hearts know to be true about God's character.\n\nFaith is like a muscle — it grows stronger through exercise. Each time you choose to trust God in a small thing, you're building the faith you'll need for bigger challenges ahead.\n\nWhat step of faith is God asking you to take today? It might be small — a prayer of surrender, a word of encouragement to someone, a decision to forgive. Whatever it is, know that God goes before you.\n\nPrayer: God, increase my faith. Help me to see with spiritual eyes and walk in obedience to Your leading. I choose to trust You today, even when I can't see the full picture. Amen.",
      verseReference: "2 Corinthians 5:7",
      verseText: "For we walk by faith, not by sight.",
      category: "Faith",
      readTime: 4,
      date: "2026-03-13",
    },
    {
      title: "The Power of Gratitude",
      content: "Gratitude transforms our perspective. When we focus on what we have rather than what we lack, something shifts in our hearts. Problems don't disappear, but they take their proper place under the shadow of God's goodness.\n\nThe apostle Paul wrote about giving thanks \"in every thing\" — not for every thing, but in every thing. There's a difference. We don't thank God for suffering, but we can thank Him in the midst of suffering because we know He is still good, still sovereign, still working.\n\nScientific research confirms what Scripture has taught for millennia: grateful people are happier, healthier, and more resilient. But for believers, gratitude goes deeper than psychology — it's an act of worship.\n\nToday, try this: before your feet hit the floor in the morning, name three things you're grateful for. Watch how it changes the trajectory of your day.\n\nPrayer: Lord, open my eyes to Your blessings today. Give me a heart of gratitude that overflows into worship. Help me to find reasons to give thanks, even in difficult seasons. Amen.",
      verseReference: "1 Thessalonians 5:18",
      verseText: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
      category: "Gratitude",
      readTime: 5,
      date: "2026-03-12",
    },
    {
      title: "God's Unfailing Love",
      content: "In a world where love is often conditional, God's love stands apart. It's not based on our performance, our worthiness, or our ability to earn it. It simply is — constant, unchanging, and freely given.\n\nRomans 8 paints one of the most beautiful pictures of God's love in all of Scripture. Nothing — not death, not life, not angels, not demons, not the present, not the future — can separate us from His love.\n\nThink about that for a moment. There is literally nothing you can do to make God love you less. And there's nothing you can do to make Him love you more. His love is complete, perfect, and unshakeable.\n\nIf you're struggling to feel loved today, remember that God's love isn't a feeling — it's a fact. It was proven at the cross and sealed by the resurrection.\n\nPrayer: Thank You, Father, for Your incredible love. Help me to truly grasp how wide, how long, how high, and how deep Your love is for me. Let Your love be the foundation of everything I do today. Amen.",
      verseReference: "Romans 8:38-39",
      verseText: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.",
      category: "Love",
      readTime: 4,
      date: "2026-03-11",
    },
    {
      title: "Trusting God's Plan",
      content: "Jeremiah 29:11 is one of the most quoted verses in the Bible, and for good reason. But to truly understand it, we need context. These words were written to people in exile — people who had lost everything and were living in a foreign land.\n\nGod's promise of a future and a hope came not in the midst of prosperity, but in the midst of pain. And notice: He didn't promise immediate rescue. He told them to settle in, build houses, plant gardens, and seek the welfare of the city where they were.\n\nSometimes God's plan involves waiting seasons. Sometimes His \"expected end\" takes longer than we'd like. But His plans are always good — always rooted in His love and wisdom.\n\nIf you're in a waiting season today, take heart. God hasn't forgotten His promises to you. He is working behind the scenes in ways you cannot yet see.\n\nPrayer: Lord, I trust Your plan for my life, even when I can't understand it. Give me patience in the waiting and faith to believe that Your timing is perfect. Amen.",
      verseReference: "Jeremiah 29:11",
      verseText: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.",
      category: "Trust",
      readTime: 5,
      date: "2026-03-10",
    },
    {
      title: "Renewing Your Mind",
      content: "Our thoughts shape our lives. What we think about determines how we feel, and how we feel influences what we do. That's why Paul's instruction to \"be transformed by the renewing of your mind\" is so revolutionary.\n\nRenewing your mind isn't a one-time event — it's a daily practice. It means intentionally replacing lies with truth, fear with faith, and worry with worship. It means filling your mind with Scripture until God's truth becomes your default thought pattern.\n\nThe world constantly tries to conform us to its patterns — through social media, news, entertainment, and cultural pressure. But we're called to a different standard. We're called to think God's thoughts after Him.\n\nStart small. Memorize one verse this week. When an anxious thought comes, replace it with a truth from God's Word. Over time, you'll notice a transformation that goes far beyond positive thinking.\n\nPrayer: Father, renew my mind today. Replace every lie I've believed with Your truth. Help me to take every thought captive and make it obedient to Christ. Transform me from the inside out. Amen.",
      verseReference: "Romans 12:2",
      verseText: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
      category: "Growth",
      readTime: 5,
      date: "2026-03-09",
    },
    {
      title: "Rest for the Weary",
      content: "In our culture of hustle and constant productivity, rest can feel like a luxury we can't afford. But Jesus extends an invitation that challenges our busy lives: \"Come unto me, all ye that labour and are heavy laden, and I will give you rest.\"\n\nThis isn't just physical rest — though our bodies certainly need it. This is soul rest. It's the deep peace that comes from laying down our burdens at the feet of Jesus and trusting Him with the outcomes.\n\nSo many of us carry weights we were never meant to bear — the weight of others' expectations, the weight of past regrets, the weight of future anxieties. Jesus invites us to exchange our heavy yoke for His light one.\n\nToday, give yourself permission to rest. Not because you've earned it, but because Jesus invites you to it. Sabbath isn't a reward for the productive — it's a gift for the weary.\n\nPrayer: Jesus, I come to You today with all my weariness. I lay down my burdens and receive Your rest. Teach me to walk in Your yoke, which is easy and light. Refresh my soul today. Amen.",
      verseReference: "Matthew 11:28",
      verseText: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
      category: "Rest",
      readTime: 4,
      date: "2026-03-08",
    },
    {
      title: "Courage for Today",
      content: "Fear is one of the most common human experiences. We fear failure, rejection, the unknown, loss, and a hundred other things. But throughout Scripture, God's most repeated command is this: \"Fear not.\"\n\nGod doesn't tell us not to fear because there's nothing to be afraid of. He tells us not to fear because He is with us. His presence is the antidote to our fear.\n\nJoshua faced an overwhelming task — leading an entire nation into enemy territory. God's encouragement to him was simple but profound: \"Be strong and of a good courage... for the Lord thy God is with thee whithersoever thou goest.\"\n\nThe same God who parted the Red Sea, who shut the mouths of lions, who raised Jesus from the dead — that God is with you today. Whatever you're facing, you don't face it alone.\n\nPrayer: Lord, I confess my fears to You. Replace them with the courage that comes from knowing You are with me. Help me to step forward in faith, trusting in Your power and presence. Amen.",
      verseReference: "Joshua 1:9",
      verseText: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.",
      category: "Courage",
      readTime: 4,
      date: "2026-03-07",
    },
    {
      title: "The Shepherd's Care",
      content: "Psalm 23 is perhaps the most beloved passage in all of Scripture. David, himself a shepherd, understood the intimate care a shepherd has for his sheep. And he saw that same care — multiplied infinitely — in God's relationship with His people.\n\n\"The Lord is my shepherd; I shall not want.\" This isn't a promise of material abundance. It's a declaration of complete trust. When the Lord is your shepherd, you have everything you truly need.\n\nGreen pastures, still waters, restored souls — these aren't just poetic images. They're descriptions of what happens when we allow God to lead us. He takes us to places of nourishment, peace, and healing.\n\nEven in the valley of the shadow of death, the shepherd's presence brings comfort. His rod protects; His staff guides. And at the end of the journey? Goodness and mercy follow us all the days of our lives.\n\nPrayer: Lord, You are my shepherd. I trust You to lead me, protect me, and provide for me. Help me to follow where You lead, even through dark valleys, knowing that You are with me. Amen.",
      verseReference: "Psalms 23:1",
      verseText: "The Lord is my shepherd; I shall not want.",
      category: "Trust",
      readTime: 5,
      date: "2026-03-06",
    },
  ];

  await db.insert(devotionalsTable).values(devotionals);
  console.log(`Inserted ${devotionals.length} devotionals`);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
